server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 3000 #启用主动失效，并且每次主动失效检测间隔为3s
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
spring:
  application:
    name: eurka-server