eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
server:
  port: 8766
  
spring:
  application:
    name: Hystrix-Ribbon
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream