server:
  port: 8081
  
spring:
  application:
    name: RabbitMQ-Consumer 
  rabbitmq:
    host: 192.168.179.128
    port: 5672
    username: root
    password: root
    
rpc-mode:
  exchange:
    name: rpc-direct-exchange
  queue:
    name:
      rpc: rpc-queue
  routing-key:
      rpc: rpc