eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.179.133:8761/eureka/
server:
  port: 9412
spring:
  application:
    name: Sleuth-Client1
  zipkin:
    base-url: http://192.168.179.133:9411