server:
  port: 8662
  
spring:
  profiles: peer2
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8661/eureka/ #指向对方端口