server:
  port: 8661
  
spring:
  profiles: peer1
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8662/eureka/ #指向对方端口